# Generated by Django 4.1.5 on 2023-03-28 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_store'),
        ('accounts', '0007_dashbord_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'جزییات محصول',
                'verbose_name_plural': 'اطلاعات جزییات محصولات',
            },
        ),
        migrations.AlterField(
            model_name='dashbord',
            name='liked',
            field=models.ManyToManyField(blank=True, to='accounts.likedproduct', verbose_name='مورد علاقه ها'),
        ),
    ]
