# Generated by Django 4.1.5 on 2023-09-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
