# Generated by Django 4.1.5 on 2023-09-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_token_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashbord',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='آدرس'),
        ),
    ]
