# Generated by Django 4.1.5 on 2023-04-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamics', '0006_category_ref_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='about_us',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='home_sentence',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='phone',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='address_contact',
            field=models.CharField(max_length=400, null=True, verbose_name='آدرس/ ارتباط با ما'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='email_contact',
            field=models.EmailField(max_length=50, null=True, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='firstsentence_contact',
            field=models.CharField(max_length=150, null=True, verbose_name='جمله اول/ ارتباط با ما'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footerrules1a',
            field=models.CharField(max_length=150, null=True, verbose_name='1aقوانین پاورقی'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footerrules1b',
            field=models.CharField(max_length=150, null=True, verbose_name='1bقوانین پاورقی'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footerrules2a',
            field=models.CharField(max_length=150, null=True, verbose_name='2aقوانین پاورقی'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footerrules2b',
            field=models.CharField(max_length=150, null=True, verbose_name='2bقوانین پاورقی'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footerrules3a',
            field=models.CharField(max_length=150, null=True, verbose_name='3aقوانین پاورقی'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footerrules3b',
            field=models.CharField(max_length=150, null=True, verbose_name='3bقوانین پاورقی'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footerrules4a',
            field=models.CharField(max_length=150, null=True, verbose_name='4aقوانین پاورقی'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footerrules4b',
            field=models.CharField(max_length=150, null=True, verbose_name='4bقوانین پاورقی'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='mobile_contact',
            field=models.CharField(max_length=50, null=True, verbose_name='تلفن همراه/ ارتباط با ما'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='openhours_contact',
            field=models.CharField(max_length=400, null=True, verbose_name='ساعات باز/ ارتباط با ما'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='phone_contact',
            field=models.CharField(max_length=50, null=True, verbose_name='تلفن/ ارتباط با ما'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='sliderdate_home',
            field=models.CharField(max_length=150, null=True, verbose_name='تاریخ اسلایدر/ صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='slidersentence_home',
            field=models.CharField(max_length=150, null=True, verbose_name='جمله اسلایدر/ صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='عنوان سایت'),
        ),
    ]
