# Generated by Django 4.1.5 on 2023-04-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamics', '0007_remove_sitesetting_about_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='address_contact',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='آدرس/ ارتباط با ما'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='facebook',
            field=models.CharField(blank=True, max_length=250, verbose_name='فیس بوک'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='firstsentence_contact',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='جمله اول/ ارتباط با ما'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footerrules1a',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='1aقوانین پاورقی'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footerrules1b',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='1bقوانین پاورقی'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footerrules2a',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='2aقوانین پاورقی'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footerrules2b',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='2bقوانین پاورقی'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footerrules3a',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='3aقوانین پاورقی'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footerrules3b',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='3bقوانین پاورقی'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footerrules4a',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='4aقوانین پاورقی'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footerrules4b',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='4bقوانین پاورقی'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='instagram',
            field=models.CharField(blank=True, max_length=250, verbose_name='اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='mobile_contact',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تلفن همراه/ ارتباط با ما'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='openhours_contact',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ساعات باز/ ارتباط با ما'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='phone_contact',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تلفن/ ارتباط با ما'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='skype',
            field=models.CharField(blank=True, max_length=250, verbose_name='اسکایپ'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='sliderdate_home',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='تاریخ اسلایدر/ صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='slidersentence_home',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='جمله اسلایدر/ صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان سایت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='tweeter',
            field=models.CharField(blank=True, max_length=250, verbose_name='توییتر'),
        ),
    ]
