# Generated by Django 4.1.5 on 2023-04-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamics', '0008_alter_sitesetting_address_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='sliderimage_home',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس اسلایدر/ صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='ایمیل/ ارتباط با ما'),
        ),
    ]
