# Generated by Django 4.1.5 on 2023-09-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamics', '0009_sitesetting_sliderimage_home_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetting',
            old_name='tweeter',
            new_name='telegram',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='skype',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='maps',
            field=models.CharField(blank=True, max_length=250, verbose_name='گوگل مپ'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=250, verbose_name='واتساپ'),
        ),
    ]
