# Generated by Django 4.1.5 on 2023-05-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderdetail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='آدرس ارسال'),
        ),
        migrations.AddField(
            model_name='order',
            name='cellphone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تلفن همراه'),
        ),
        migrations.AddField(
            model_name='order',
            name='homephone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تلفن ثابت'),
        ),
    ]
