# Generated by Django 4.1.5 on 2023-10-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_address_order_cellphone_order_homephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(default=False, max_length=50, verbose_name='فرستاده شده'),
        ),
    ]
