# Generated by Django 4.1.5 on 2023-03-18 09:34

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_price_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path_comment_profiles, verbose_name='تصویر'),
        ),
    ]
