# Generated by Django 4.1.5 on 2023-03-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productcomment_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcomment',
            old_name='image',
            new_name='profile',
        ),
    ]
