# Generated by Django 4.1.5 on 2023-03-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_rename_image_productcomment_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.IntegerField(default=5, verbose_name='موجودی'),
            preserve_default=False,
        ),
    ]
