# Generated by Django 4.1.5 on 2023-04-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='امتیاز'),
        ),
    ]
