# Generated by Django 4.1.5 on 2023-04-09 13:55

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_productcomment_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='profile',
            field=models.ImageField(blank=True, default='profiles/0.png', null=True, upload_to=products.models.upload_image_path_comment_profiles, verbose_name='تصویر'),
        ),
    ]
