# Generated by Django 4.1.5 on 2023-05-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_blog_blogdetail_delete_incomingproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ترتیب'),
        ),
    ]
