# Generated by Django 4.1.5 on 2023-07-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_blogdetail_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_end', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
