# Generated by Django 4.1.5 on 2023-07-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_discounttimer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounttimer',
            name='time_end',
            field=models.DateTimeField(blank=True),
        ),
    ]
