# Generated by Django 4.1.5 on 2023-07-15 08:25

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_discounttimer_time_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='discounttimer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path_discount, verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='discounttimer',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='discounttimer',
            name='text',
            field=models.TextField(null=True, verbose_name='نظر'),
        ),
    ]
