# Generated by Django 4.1.5 on 2023-07-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_discounttimer_image_discounttimer_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discounttimer',
            name='active',
            field=models.BooleanField(default=False, verbose_name='فعال / غیرفعال'),
        ),
    ]
