# Generated by Django 4.1.5 on 2023-07-30 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_discounttimer_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discounttimer',
            options={'verbose_name': 'تایمر', 'verbose_name_plural': 'تایمر ها'},
        ),
    ]
