# Generated by Django 4.1.5 on 2023-10-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_productatrrs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAtrrs',
            new_name='ProductAtrr',
        ),
    ]
